const express = require('express');
const jwt = require('jsonwebtoken');
const supabase = require('../db/supabase');
const supabaseLogs = require('../db/supabaseLogs');
const authMiddleware = require('../middleware/auth');

const router = express.Router();
const IST_TZ = 'Asia/Kolkata';

const { getGymStatus } = require('../utils/gymStatus');
const { getNowIST, getTodayISTStr } = require('../utils/dateUtils');

const getIstNow = () => {
  const now = getNowIST();
  const day = now.setLocale('en-US').toFormat('cccc').toLowerCase(); // monday, tuesday, etc.
  const date = now.toISODate(); // YYYY-MM-DD
  const time = now.toFormat('HH:mm:ss');
  return { now: now.toJSDate(), day, date, time };
};

const dateFromIst = (dateStr) => {
  const [y, m, d] = dateStr.split('-').map(Number);
  const { DateTime } = require('luxon');
  return DateTime.fromObject({ year: y, month: m, day: d }, { zone: 'Asia/Kolkata' }).toJSDate();
};

// checkGymOpen logic moved to utils/gymStatus.js

// ─── Helper: Get Last Valid Gym Day ──────────────────────────────────────────
async function getLastValidGymDay(beforeDateStr) {
  let checkDate = dateFromIst(beforeDateStr);
  let safety = 0;
  
  while (safety < 30) { // Check up to last 30 days
    safety++;
    checkDate.setDate(checkDate.getDate() - 1);
    const dateStr = new Intl.DateTimeFormat('en-CA', { timeZone: IST_TZ }).format(checkDate);
    const dayName = ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'][checkDate.getDay()];
    
    // 1. Check if it was a holiday
    const { data: holiday } = await supabase.from('holidays').select('*').eq('date', dateStr).single();
    if (holiday && holiday.is_closed) continue;
    
    // 2. Check weekly schedule
    const { data: schedule } = await supabase.from('weekly_schedule').select('*').eq('day_of_week', dayName).single();
    if (schedule && !schedule.is_open) continue;
    
    return dateStr;
  }
  return null;
}

// ─── Generate Dynamic QR Token (Admin displays this) ─────────────────────────
router.get('/generate', authMiddleware(['admin']), async (req, res) => {
  try {
    const gymStatus = await getGymStatus(supabase);
    const token = jwt.sign(
      { type: 'attendance_qr' },
      process.env.JWT_SECRET,
      { expiresIn: '90s' } // 60s official + 30s network buffer
    );
    
    if (!gymStatus.is_open) {
      console.warn(`[QR] Generated by Admin despite: ${gymStatus.holiday_reason || 'Closed'}`);
      return res.json({ 
        success: true, 
        message: 'QR generated (Admin Bypass)', 
        warning: gymStatus.holiday_reason || 'Gym is closed', 
        data: { qr_code: token, expires_in: 60 }, 
        error_code: null 
      });
    }

    res.json({ success: true, message: 'QR generated', data: { qr_code: token, expires_in: 60 }, error_code: null });
  } catch(e) {
    res.status(500).json({ success: false, message: e.message, error_code: 'GENERATE_ERROR' });
  }
});

// ─── Scan QR Token (User scans this with their phone) ────────────────────────
router.post('/scan', authMiddleware(['user']), async (req, res) => {
  const { code_hash } = req.body;
  if (!code_hash) return res.status(400).json({ success: false, message: 'QR token required', error_code: 'MISSING_QR' });

  // 1. Gym Status Check
  const gymStatus = await getGymStatus(supabase);
  if (!gymStatus.is_open) {
    const reason = gymStatus.is_holiday ? `Holiday: ${gymStatus.holiday_reason}` : "Gym is currently closed (Outside batch hours or schedule)";
    return res.status(403).json({ success: false, message: reason, error_code: 'GYM_CLOSED' });
  }

  // 2. Token Verification
  try {
    if (!process.env.JWT_SECRET) {
      console.error('[QR SCAN] JWT_SECRET is missing from environment!');
    }
    const decoded = jwt.verify(code_hash, process.env.JWT_SECRET);
    if (decoded.type !== 'attendance_qr') throw new Error('Invalid token type');
    console.log(`[QR SCAN] Token verified for user: ${req.user.userId}`);
  } catch (err) {
    const isExpired = err.name === 'TokenExpiredError';
    console.warn(`[QR SCAN] Verification failed: ${err.message}`);
    
    return res.status(400).json({ 
      success: false, 
      message: isExpired ? "QR Code has expired. Please scan the new one." : "Invalid QR Code", 
      error_code: isExpired ? 'QR_EXPIRED' : 'INVALID_QR',
      debug: { error: err.message, token_start: code_hash.substring(0, 10) }
    });
  }

  const user_id = req.user.userId;
  const user_role = req.user.role;
  const { now, date: today, day } = getIstNow();
  const dayNameLower = day.toLowerCase();

  // 3. User Membership & Batch Check
  const { data: userRecord, error: userErr } = await supabase.from('users')
    .select('*, batches(days_active)')
    .eq('id', user_id)
    .single();

  if (userErr || !userRecord) {
    return res.status(401).json({ success: false, message: 'User record not found', error_code: 'AUTH_ERROR' });
  }

  // A. Auto-Expiry Logic
  if (userRecord.membership_expiry && userRecord.membership_expiry < today) {
    if (userRecord.status === 'active') {
      await supabase.from('users').update({ status: 'inactive' }).eq('id', user_id);
    }
    return res.status(403).json({ success: false, message: 'Membership expired. Please renew at the desk.', error_code: 'EXPIRED' });
  }

  // B. Inactive & Freeze Status Block
  if (userRecord.is_frozen) {
    return res.status(403).json({ success: false, message: 'Membership is currently frozen. Contact office to unfreeze.', error_code: 'FROZEN' });
  }

  if (userRecord.status !== 'active') {
    return res.status(403).json({ success: false, message: `Account status is ${userRecord.status}. Please contact admin.`, error_code: 'INACTIVE' });
  }

  // C. Batch Day Enforcement
  const batchDays = userRecord.batches?.days_active || [];
  if (batchDays.length > 0 && !batchDays.includes(dayNameLower)) {
    return res.status(403).json({ success: false, message: `Your batch is not active on ${dayNameLower.toUpperCase()}.`, error_code: 'BATCH_RESTRICTED' });
  }

  // 4. Attendance & Streak Logic
  const { data: existing, error: fetchErr } = await supabaseLogs.from('attendance')
    .select('*').eq('user_id', user_id).eq('date', today).maybeSingle();

  if (fetchErr) {
    return res.status(500).json({ success: false, message: 'Database error fetching attendance', error: fetchErr.message });
  }

  let action = '';
  const nowIso = getNowIST().toISO();
  let streakData = null;

  if (!existing) {
    // Check In & Streak Processing
    const lastValidDay = await getLastValidGymDay(today);
    let newStreak = 1;
    
    if (userRecord.streak_last_updated === lastValidDay) {
      newStreak = (userRecord.current_streak || 0) + 1;
    } else if (userRecord.streak_last_updated === today) {
      newStreak = userRecord.current_streak; // Already updated today
    }

    const newBest = Math.max(userRecord.best_streak || 0, newStreak);
    
    const { error: attErr } = await supabaseLogs.from('attendance').insert([{ user_id, date: today, time_in: nowIso }]);
    if (attErr) return res.status(400).json({ success: false, message: `Check-in failed: ${attErr.message}`, error_code: 'ATTENDANCE_ERROR' });
    
    const { error: userUpdateErr } = await supabase.from('users').update({ 
      current_streak: newStreak, 
      best_streak: newBest,
      streak_last_updated: today 
    }).eq('id', user_id);
    
    if (userUpdateErr) console.error('Streak update failed:', userUpdateErr);
    
    action = 'IN';
    streakData = { current: newStreak, best: newBest, isNewRecord: newBest > (userRecord.best_streak || 0) };
  } else if (!existing.time_out) {
    const { error } = await supabaseLogs.from('attendance').update({ time_out: nowIso }).eq('id', existing.id);
    if (error) return res.status(400).json({ success: false, message: error.message, error_code: 'ATTENDANCE_ERROR' });
    action = 'OUT';
  } else {
    return res.status(400).json({ success: false, message: 'You have already checked out today', error_code: 'ALREADY_COMPLETED' });
  }

  // 5. Logging & Response
  // 5. Logging & Response (removed)

  res.json({ success: true, message: `Checked ${action} successfully`, data: { action, streak: streakData, user: { name: userRecord.name, roll_no: userRecord.roll_no } }, error_code: null });
});


module.exports = router;
